import assets from "./assets";

const NFTData = [
  {
    id: "NFT-01",
    name: "Moon Herself",
    creator: "Sweaniz Noubagh",
    price: 4.25,
    description:
      "These images are in the rarest form generated by an AI",
    image: assets.nft01,
    bids: [
      {
        id: "BID-11",
        name: "Olia Misiuk",
        price: 4.25,
        image: assets.person02,
        date: "December 12, 2021 at 12:10 PM",
      },
      {
        id: "BID-12",
        name: "NFT Queen",
        price: 4.5,
        image: assets.person03,
        date: "December 27, 2021 at 1:50 PM",
      },
      {
        id: "BID-13",
        name: "Rosa Van de Buurt",
        price: 4.75,
        image: assets.person04,
        date: "December 31, 2021 at 3:50 PM",
      },
    ],
  },
  {
    id: "NFT-02",
    name: "Warped by Time",
    creator: "Sweaniz Noubagh",
    price: 7.25,
    description:
      "Generated by an AI",
    image: assets.nft02,
    bids: [
      {
        id: "BID-21",
        name: "Olia Misiuk",
        price: 7.05,
        image: assets.person04,
        date: "December 12, 2021 at 12:10 PM",
      },
    ],
  },
  {
    id: "NFT-03",
    name: "Mother Universe",
    creator: "James Web Telescope",
    price: 95.25,
    description:
      "Generated by an AI",
    image: assets.nft03,
    bids: [
      {
        id: "BID-31",
        name: "Olia Misiuk",
        price: 95.25,
        image: assets.person02,
        date: "December 12, 2021 at 12:10 PM",
      },
      {
        id: "BID-32",
        name: "NFT Queen",
        price: 95.5,
        image: assets.person03,
        date: "December 27, 2021 at 1:50 PM",
      },
    ],
  },
  {
    id: "NFT-04",
    name: "VanGogh Speed",
    creator: "Putri Intan",
    price: 54.25,
    description:
      "Generated by an AI",
    image: assets.nft04,
    bids: [
      {
        id: "BID-41",
        name: "Olia Misiuk",
        price: 56.25,
        image: assets.person02,
        date: "December 12, 2021 at 12:10 PM",
      },
      {
        id: "BID-42",
        name: "NFT Queen",
        price: 54.25,
        image: assets.person03,
        date: "December 27, 2021 at 1:50 PM",
      },
      {
        id: "BID-43",
        name: "Rosa Van de Buurt",
        price: 55.15,
        image: assets.person04,
        date: "December 31, 2021 at 3:50 PM",
      },
      {
        id: "BID-44",
        name: "Vincent Swift",
        price: 54.15,
        image: assets.person02,
        date: "December 31, 2021 at 3:50 PM",
      },
    ],
  },
  {
    id: "NFT-05",
    name: "Colorful Void",
    creator: "David doe",
    price: 10.25,
    description:
      "Generated by an AI",
    image: assets.nft05,
    bids: [
      {
        id: "BID-51",
        name: "Olia Misiuk",
        price: 10.25,
        image: assets.person02,
        date: "December 12, 2021 at 12:10 PM",
      },
    ],
  },
  
];

export { NFTData };
